coverage:
  precision: 3
  round: down
  range: "70...100"
  status:
    project:
      default: off
      client:
        flags: client
      server:
        flags: server

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

flags:
  client:
    paths:
      - client/
  server:
    paths:
      - server/
