coverage:
  precision: 3
  round: down
  range: "70...100"
  status:
    project:
      default: off
      client-ts:
        flags: client-ts
      client-reasonml:
        flags: client-reasonml
      server:
        flags: server

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

flags:
  client-ts:
    paths:
      - client-ts/
  client-reasonml:
    paths:
      - client-reasonml/
  server:
    paths:
      - server/
