language: node_js

notifications:
  email: false

cache:
  directories:
    - client/node_modules
    - server/node_modules

matrix:
  include:
    - env: BUILD_TARGET=client-ts
    - env: BUILD_TARGET=server

git:
  depth: 3

install: source ./travis/install.sh

script: source ./travis/script.sh

after_success: source ./travis/after_success.sh
